### ISSUE TITLE
Bump Version on NPM to publish Readme

### ISSUE THREAD

**Issue by rtablada** [socialwifi/ember-adminlte-components#1]
👋 Ryan from EmberWeekly here just wanted to give you all a heads up that the NPM readme is out of date and doesn't have much info there.

NPM publishes the readme for packages when you run `npm publish` so right now the readme is really sparse on NPM.

This is important since major resources (Ember Weekly, EmberObserver.com, Emberaddons.com) all link to the NPM package so having a good readme on NPM is important for user adoption.

If you can bump and publish a new patch version to NPM it should update the readme there.

---
Anyway!

Thanks for these components, I've been a user of AdminLTE for years and these components look really cool.

**Comment by riklaunim** [comment]
I've added the readme yesterday, after package release. I'll likely do some readme tuning and then bump the version alongside some 2.4 fixes.

I also have some workflow components/shared code that isn't fully included yet but that's a story for a bigger update or separate package.

**Comment by riklaunim** [comment]
And released.
